api_version = "2024-07"

[[extensions]]
handle = "threshold-nodiscounts-taxinc"
name = "t:name"
description = "t:description"
type = "function"

  [[extensions.targeting]]
  target = "purchase.shipping-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = "cargo wasi build --release"
  path = "target/wasm32-wasi/release/threshold-nodiscounts-taxinc.wasm"
  watch = [ "src/**/*.rs" ]

  [extensions.ui.paths]
  create = "/"
  details = "/"
