api_version = "unstable"

[[extensions]]
name = "t:name"
handle = "buy2get2free"
type = "function"

description = "t:description"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/generate_cart_run.graphql"
  export = "generate_cart_run"

  [[extensions.targeting]]
  target = "cart.delivery-options.discounts.generate.run"
  input_query = "src/generate_delivery_run.graphql"
  export = "generate_delivery_run"

  [extensions.build]
  command = "cargo wasi build --release"
  path = "target/wasm32-wasi/release/buy2get2free.wasm"
  watch = [ "src/**/*.rs" ]
